### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/sawkatokaleya#4]
Mukuni is probably https://glottolog.org/resource/languoid/id/lenj1248, the other missing ones look like dialects of Toka-Leya (https://www.sil.org/resources/publications/entry/80878) which we should check with Harald about getting into glottolog.

**Comment by chrzyki** [comment]
Thanks for checking @SimonGreenhill, will update and contact Harald.

**Comment by Kristina-Pianykh** [comment]
As far as I understood, there are three Toka-Leya dialects under investigation, namely Mukuni, Sekute and Musukotwani:

> A lexical and phonostatistical comparison was also done between three varieties or dialects of Toka-Leya. The Mukuni and Sekute variants have an equally high percentage of lexical similarity with each other as well as with the Musukotwani variety.

Lenje seems to be something different from Toka-Leya:

> When the groups interviewed were asked which language is most similar to Toka-Leya, 63% said Tonga, 38% said Lenje and 13% said Lozi.

> Further work needs to be done to determine the grammatical similarities of Toka-Leya with Tonga or Lenje.

> Of the nine languages that were compared with Toka-Leya, Lenje has the third highest lexical similarity with Toka-Leya.

Also when I checked the section with Toka-Leya people, I found the following:
> The Toka-Leya population resides mostly in two administrative districts of Zambia’s Southern Province: Kazungula District and Livingstone District.

Table 5 on page 10 lists the wards of the Kazungula District, among them Mukuni, Sekute and Musukotwani.

**Comment by chrzyki** [comment]
Thanks @Kristina-Pianykh. Asked Harald for input on this.

**Comment by chrzyki** [comment]
Dear both,

musu1242 & seku1239 will be prepared for Glottolog. Harald says that Mukuni in the report must be Leya Mukuni.

**Comment by Kristina-Pianykh** [comment]
Great news, thank you very much for the update!
